apiVersion: v1
data:
  AWS_B64ENCODED_CREDENTIALS: VzJSbFptRjFiSFJkQ21GM2MxOWhZMk5sYzNOZmEyVjVYMmxrSUQwZ1FVdEpRVk5ZVUZGVlNrSTJURXBYVlRKQlNUY0tZWGR6WDNObFkzSmxkRjloWTJObGMzTmZhMlY1SUQwZ1JuaG1SMXBGY0VVdlpIRkdRVWROVFhGSGJEVkZjMDVpVlRCTFF6RlJSV05WVVVsa2FGcG5Rd3B5WldkcGIyNGdQU0IxY3kxbFlYTjBMVElLQ2c9PQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: capi-cluster-token
  namespace: capi-cluster-kubeaid-demo
